### ISSUE TITLE
Which network strucetures are supported by  lottery_ticket_pruner?

### ISSUE THREAD

**Issue by NewEricWang** [jim-meyer/lottery_ticket_pruner#27]
Can  the project prune neural network with any structure?
Or it only supports specific structure network, such as CNN.

**Comment by jim-meyer** [comment]
This project supports pruning of arbitrary neural networks that have any of [these layers](https://github.com/jim-meyer/lottery_ticket_pruner/blob/master/lottery_ticket_pruner/lottery_ticket_pruner.py#L226-L241):
'Conv1D',
'Conv2D',
'Conv2DTranspose',
'Conv3D',
'Conv3DTranspose',
'Convolution1D',
'Convolution2D',
'Convolution2DTranspose',
'Convolution3D',
'Convolution3DTranspose',
'Dense',
'DepthwiseConv2D',
'SeparableConv1D',
'SeparableConv2D',
'SeparableConvolution1D',
'SeparableConvolution2D'

**Comment by NewEricWang** [comment]
Thanks for your prompt response！
